name: Release

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      IS_PRERELEASE: ${{ github.event.release.prerelease }}
    steps:
      - uses: actions/checkout@v2

      - name: Show event action
        run: echo "The calling event was a ${{ github.event.action }}"
        
#       - name: Test Payload Info
#         run: echo "${{ toJSON(github.event) }}"
      
      - name: Print if this is a prerelease
        if: ${{ env.IS_PRERELEASE == true }}
        run: echo "This is a prerelease! $IS_PRERELEASE"

      - name: Print if this is NOT a prerelease
        if: ${{ env.IS_PRERELEASE == false }}
        run: echo "Not a prerelease. $IS_PRERELEASE"
